[versions]
agp = "8.12.3"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
logger = "2.2.0"
timberVersion = "5.0.1"
koin = "3.5.3"

[libraries]
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
logger = { group = "com.orhanobut", name = "logger", version.ref = "logger" }

# Koin
koin-android = {group="io.insert-koin", name="koin-android", version.ref = "koin"}
koin-androidx-compose = {group="io.insert-koin", name="koin-androidx-compose", version.ref = "koin"}
koin-core = {group="io.insert-koin", name="koin-core", version.ref = "koin"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

[bundles]
koin= [
    "koin-core",
    "koin-android",
    "koin-androidx-compose"
]

